### Variables 
@apiurl = http://127.0.0.1:7000

# note : rmber to change de ark for valid arks


### load invalido 1
POST {{apiurl}}/update HTTP/1.1
Content-Type: application/json

{
    "dnam_pk": "R1",
    "items": [ 
        {"oai_id" : "a" , "url" : "invalida"},
        {"oai_id" : "b" , "url" : "http://uol.com"},
        {"oai_id" : "c" , "url" : "http://uol.com"},
        {"oai_id" : "d" , "url" : "http://uol.com"}
    ]
    
}

### load invalido 2
POST {{apiurl}}/update HTTP/1.1
Content-Type: application/json

{
    "dnam_pk": "0xINVALIDA_NOT_VALID_INVALIDA_4d162f",
    "items": [ 
        {"oai_id" : "a" , "url" : "invalida"}
    ]
    
}

### load invalido 3
POST {{apiurl}}/update HTTP/1.1
Content-Type: application/json

{
    "dnam_pk": "0xINVALIDA_NOT_VALID_INVALIDA_4d162f",
    "items": [ 
        {"oai_id" : "a" , "url" : "invalida"},
        {"dark_id" : "b" , "url" : "http://uol.com"}
    ]
    
}

### load invalida 4
POST {{apiurl}}/update HTTP/1.1
Content-Type: application/json

{
    "dnam_pk": "0xINVALIDA_NOT_VALID_INVALIDA_4d162f",
    "items": [ 
        {"dark_id" : "8033/fkwf300000004h" , "url" : "http:/gov.com/"}
    ]
    
}

### load valida 1
POST {{apiurl}}/update HTTP/1.1
Content-Type: application/json

{
    "dnam_pk": "0xINVALIDA_NOT_VALID_INVALIDA_4d162f",
    "items": [ 
        {"dark_id" : "8033/fkwf30000003gg" , "url" : "http://uol.com/up1"}
    ]
    
}


### load valida 2
POST {{apiurl}}/update HTTP/1.1
Content-Type: application/json

{
    "dnam_pk": "0xINVALIDA_NOT_VALID_INVALIDA_4d162f",
    "items": [ 
        {"dark_id" : "8033/fkwf300000001n" , "url" : "http://nova.com/up1"},
        {"dark_id" : "8033/fkwf3000000028" , "url" : "http://new.com/up1"},
        {"dark_id" : "8033/fkwf300000004h" , "url" : "http://nueva.com/up1"}        
    ]
    
}

### load invalida 4
POST {{apiurl}}/update HTTP/1.1
Content-Type: application/json

{
    "dnam_pk": "0xINVALIDA_NOT_VALID_INVALIDA_4d162f",
    "items": [ 
        {"dark_id" : "8033/fkwf300000004h" , "url" : "http:/gov.com/"},
        {"dark_id" : "8033/fkwf3000000028" , "url" : "http://tudook.com/update"}
    ]
    
}

