C4Context
    %% @config(../mmd_config.json)
    title Authenticaded Users 
    Boundary(c0, "Hyperdrive") {
        Component(h_core,Hyperdrive Core Module, "")
        Component(h_auth,Hyperdrive Authentication Module, "")
        Component(h_conf,Hyperdrive Configuration Module, "")
        Component(h_query,Hyperdrive Query Module, "")
    }

    Person(pp,"Curator","private")
    Person(mu,"Manager","private")
    BiRel(pp, h_core, "Uses")
    Rel(pp, h_auth, "authenticate")

    Rel(mu, h_auth, "Configure")
    Rel(mu, h_conf, "Configure")


    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")