C4Context
    %% @config(../mmd_config.json)
    title Hyperdrive Modules

    Boundary(c0, "Hyperdrive") {
        Component(h_core,Hyperdrive Core Module, "")
        Component(h_auth,Hyperdrive Auth Module, "")
        Component(h_conf,Hyperdrive Configuration Module, "")
        Component(h_query,Hyperdrive Query Module, "")
    }
    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")